services:
  qdrant:
    image: qdrant/qdrant:v1.9.2
    ports: ["6333:6333"]
    volumes:
      - qdrant_storage:/qdrant/storage
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:6333/readyz >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 45s   # ↑ was 15s; Windows spins slower
volumes:
  qdrant_storage:
